name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: started
      run: echo "CI started"
    - name: job finished
      run: echo "CI finished"
